# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b039f349b588d5ad0da68771e1e6eba3f82dc44aa749a4433beda23b21e3554c1d50c2319efe897809df49d085377a8390547b7b48408b94d43e166fbc41a58

test:
  secret_key_base: 29c61aaadec39e3a62af2641928918d6ab176ee47105607f364015a3018772807111baaae2a79dec54120063044813af12ef786d2f1b0560987f37deabaef7d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
